### ISSUE TITLE
deleteBucket() not deleting the bucket.

### ISSUE THREAD

**Issue by sweta96** [Robothy/local-s3#31]
Scenario: I added objects using putObject() and then removed the objects using deleteObject(), after which i am trying deleteBucket(), it does not delete the bucket with exception that the bucket is not empty.

**Comment by Robothy** [comment]
This is an expected behavior, according to the API reference. https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteBucket.html

**Comment by Robothy** [comment]
@sweta96 Could you provide more detailed steps?

**Comment by sweta96** [comment]
Steps:
1. I created a new container, client and bucket.
2. using the client added objects to the new bucket using putObject().
3. removed the objects added using deleteObject().
4. Since the bucket is empty as all the objects have been removed, I tried deleting the bucket. When deleting the bucket i am getting the error that the bucket cannot be deleted as it is not empty.

```The bucket 'testingbucket' is not empty.```

**Comment by Robothy** [comment]
Call [ListObjectVersions](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html) to check if there are delete markers in the bucket. From AmazonS3 [API reference](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteBucket.html):
> All objects (including all object versions and delete markers) in the bucket must be deleted before the bucket itself can be deleted.

**Comment by Robothy** [comment]
The delete marker will be created even if bucket versioning is not enabled. The delete marker has a `"null"` string version number. This behavior is the same as Amazon S3.

Assume we have an empty bucket, which is not enabled object versioning.
+ Put object `a.txt`. Then the bucket has an object `a.txt`, whose version number is `"null"`.
+ Delete object `a.txt` without the version number. Then the bucket has a delete marker `a.txt`, whose version number is `"null"`.
+ Delete the delete marker of `a.txt` with version number `"null"`. Then the delete marker is removed from the bucket. The bucket is empty now, and you can delete the bucket.

Therefore, you need to call `deleteVersion("bucket name", "object key", "null")` instead of `deleteObject()` to remove the object. The former won't generate a delete marker.

**Comment by sweta96** [comment]
I checked the behaviour with Amazon S3. When i do deleteObject(), i do not see deleteMarker getting created when i list using listVersions().

**Comment by Robothy** [comment]
Did you open the toggle "Show versions"?

![image](https://user-images.githubusercontent.com/10234260/210585515-da147bc9-91b8-4085-acc6-4c00feb2f717.png)

**Comment by Robothy** [comment]
@sweta96 I wrote a short test case that hits the real AmazonS3 API. It generates a delete marker even though I disabled the bucket versioning. Please take double-check.

![image](https://user-images.githubusercontent.com/10234260/210587822-ba5bfa02-ebe8-42d4-84f0-7cdf67016a28.png)

**Comment by sweta96** [comment]
![image (5)](https://user-images.githubusercontent.com/27861304/210693470-dd7bf998-40b5-4545-8d18-9fcbed585db6.png)

@Robothy  could try with a bucket without version itself. 

"show versions" option will not even come if bucket is not version enabled

**Comment by sweta96** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html

After you version-enable a bucket, it can never return to an unversioned state. But you can suspend versioning on that bucket.

We are using a bucket without versioning.

**Comment by sweta96** [comment]
I ran a test with the two types of bucket (with versioning and without versioning)

This is my observation,

isDeleteMarker=false (for "bucket-without-versioning")
isDeleteMarker=true (for "bucket-with-versioning" )

**Comment by Robothy** [comment]
https://github.com/Robothy/local-s3/pull/41

**Comment by Robothy** [comment]
@sweta96 This bug is fixed in the latest Docker Image. Feel free to reopen this issue if you think it doesn't work as expected.
